version: '3'
services:
    app:
        container_name: file-share-app
        build:
            context: ../../
            dockerfile: Dockerfile
        volumes:
            - ../../:/var/www/html
            - ../php.ini:/usr/local/etc/php/php.ini
        working_dir: /var/www/html
        ports:
            - 80:80
        networks:
            - file-share

    pgsql:
        container_name: file-share-db
        image: postgres:10.0
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "postgres"
            POSTGRES_DB: "postgres"
        volumes:
            - ../pgsql:/var/lib/postgresql/data
        networks:
            - file-share

networks:
  file-share:
    driver: "bridge"
    external: true
